# .github/workflows/sync.yml
name: Daily Data Sync

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

# YENİ: Ortam değişkenlerini en üst seviyede tanımla
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data sync script
      # Artık her adımda env tanımlamaya gerek yok, çünkü en üstte tanımlandı.
      # Bu, değişkenlerin tüm job boyunca geçerli olmasını sağlar.
      run: python sync_data.py